config/routes.rb
JpmobileTest::Application.routes.draw do |map|
  resources :guestbooks

end

app/models/guestbook.rb
class Guestbook < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/guestbooks_controller.rb
class GuestbooksController < ApplicationController
  trans_sid :always

  # GET /guestbooks
  # GET /guestbooks.xml
  def index
    session[:t] = Time.now

    @guestbooks = Guestbook.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @guestbooks }
    end
  end

  # GET /guestbooks/1
  # GET /guestbooks/1.xml
  def show
    @guestbook = Guestbook.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @guestbook }
    end
  end

  # GET /guestbooks/new
  # GET /guestbooks/new.xml
  def new
    @guestbook = Guestbook.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @guestbook }
    end
  end

  # GET /guestbooks/1/edit
  def edit
    @guestbook = Guestbook.find(params[:id])
  end

  # POST /guestbooks
  # POST /guestbooks.xml
  def create
    @guestbook = Guestbook.new(params[:guestbook])

    respond_to do |format|
      if @guestbook.save
        format.html { redirect_to(@guestbook, :notice => 'Guestbook was successfully created.') }
        format.xml  { render :xml => @guestbook, :status => :created, :location => @guestbook }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @guestbook.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /guestbooks/1
  # PUT /guestbooks/1.xml
  def update
    @guestbook = Guestbook.find(params[:id])

    respond_to do |format|
      if @guestbook.update_attributes(params[:guestbook])
        format.html { redirect_to(@guestbook, :notice => 'Guestbook was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @guestbook.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /guestbooks/1
  # DELETE /guestbooks/1.xml
  def destroy
    @guestbook = Guestbook.find(params[:id])
    @guestbook.destroy

    respond_to do |format|
      format.html { redirect_to(guestbooks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guestbooks_helper.rb
module GuestbooksHelper
end

app/views/guestbooks/_form.html.erb
<%= form_for(@guestbook) do |f| %>
  <% if @guestbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guestbook.errors.count, "error") %> prohibited this guestbook from being saved:</h2>

      <ul>
      <% @guestbook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guestbooks/edit.html.erb
<h1>Editing guestbook</h1>

<%= render 'form' %>

<%= link_to 'Show', @guestbook %> |
<%= link_to 'Back', guestbooks_path %>

app/views/guestbooks/index.html.erb
<h1>Listing guestbooks</h1>

<table>
  <tr>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @guestbooks.each do |guestbook| %>
  <tr>
    <td><%= guestbook.comment %></td>
    <td><%= link_to 'Show', guestbook %></td>
    <td><%= link_to 'Edit', edit_guestbook_path(guestbook) %></td>
    <td><%= link_to 'Destroy', guestbook, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Guestbook', new_guestbook_path %>

app/views/guestbooks/index_mobile.html.erb
<h1>ゲストブック(mobile)</h1>

<table>
  <tr>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @guestbooks.each do |guestbook| %>
  <tr>
    <td><%= guestbook.comment %></td>
    <td><%= link_to 'Show', guestbook %></td>
    <td><%= link_to 'Edit', edit_guestbook_path(guestbook) %></td>
    <td><%= link_to 'Destroy', guestbook, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Guestbook', new_guestbook_path %>

app/views/guestbooks/index_mobile_android.html.erb
<h1>ゲストブック(android)</h1>

<table>
  <tr>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @guestbooks.each do |guestbook| %>
  <tr>
    <td><%= guestbook.comment %></td>
    <td><%= link_to 'Show', guestbook %></td>
    <td><%= link_to 'Edit', edit_guestbook_path(guestbook) %></td>
    <td><%= link_to 'Destroy', guestbook, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Guestbook', new_guestbook_path %>

app/views/guestbooks/index_mobile_au.html.erb
<h1>ゲストブック(au)</h1>

<table>
  <tr>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @guestbooks.each do |guestbook| %>
  <tr>
    <td><%= guestbook.comment %></td>
    <td><%= link_to 'Show', guestbook %></td>
    <td><%= link_to 'Edit', edit_guestbook_path(guestbook) %></td>
    <td><%= link_to 'Destroy', guestbook, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Guestbook', new_guestbook_path %>

app/views/guestbooks/index_mobile_docomo.html.erb
<h1>ゲストブック(docomo)</h1>

<table>
  <tr>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @guestbooks.each do |guestbook| %>
  <tr>
    <td><%= guestbook.comment %></td>
    <td><%= link_to 'Show', guestbook %></td>
    <td><%= link_to 'Edit', edit_guestbook_path(guestbook) %></td>
    <td><%= link_to 'Destroy', guestbook, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Guestbook', new_guestbook_path %>

app/views/guestbooks/index_mobile_iphone.html.erb
<h1>ゲストブック(iphone)</h1>

<table>
  <tr>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @guestbooks.each do |guestbook| %>
  <tr>
    <td><%= guestbook.comment %></td>
    <td><%= link_to 'Show', guestbook %></td>
    <td><%= link_to 'Edit', edit_guestbook_path(guestbook) %></td>
    <td><%= link_to 'Destroy', guestbook, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Guestbook', new_guestbook_path %>

app/views/guestbooks/index_mobile_smart_phone.html.erb
<h1>ゲストブック(smartphone)</h1>

<table>
  <tr>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @guestbooks.each do |guestbook| %>
  <tr>
    <td><%= guestbook.comment %></td>
    <td><%= link_to 'Show', guestbook %></td>
    <td><%= link_to 'Edit', edit_guestbook_path(guestbook) %></td>
    <td><%= link_to 'Destroy', guestbook, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Guestbook', new_guestbook_path %>

app/views/guestbooks/index_mobile_softbank.html.erb
<h1>ゲストブック(softbank)</h1>

<table>
  <tr>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @guestbooks.each do |guestbook| %>
  <tr>
    <td><%= guestbook.comment %></td>
    <td><%= link_to 'Show', guestbook %></td>
    <td><%= link_to 'Edit', edit_guestbook_path(guestbook) %></td>
    <td><%= link_to 'Destroy', guestbook, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Guestbook', new_guestbook_path %>

app/views/guestbooks/index_smart_phone.html.erb
<h1>ゲストブック(SmartPhone)</h1>

<table>
  <tr>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @guestbooks.each do |guestbook| %>
  <tr>
    <td><%= guestbook.comment %></td>
    <td><%= link_to 'Show', guestbook %></td>
    <td><%= link_to 'Edit', edit_guestbook_path(guestbook) %></td>
    <td><%= link_to 'Destroy', guestbook, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Guestbook', new_guestbook_path %>

app/views/guestbooks/index_smart_phone_iphone.html.erb
<h1>ゲストブック(iPhone)</h1>

<table>
  <tr>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @guestbooks.each do |guestbook| %>
  <tr>
    <td><%= guestbook.comment %></td>
    <td><%= link_to 'Show', guestbook %></td>
    <td><%= link_to 'Edit', edit_guestbook_path(guestbook) %></td>
    <td><%= link_to 'Destroy', guestbook, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Guestbook', new_guestbook_path %>

app/views/guestbooks/new.html.erb
<h1>New guestbook</h1>

<%= render 'form' %>

<%= link_to 'Back', guestbooks_path %>

app/views/guestbooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Comment:</b>
  <%= @guestbook.comment %>
</p>


<%= link_to 'Edit', edit_guestbook_path(@guestbook) %> |
<%= link_to 'Back', guestbooks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JpmobileTest</title>
  <% if false -%><meta http-equiv="Content-Type" content="text/html; charset=Shift_JIS" /><% end -%>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application_mobile.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JpmobileTest</title>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <h1>mobile</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/application_mobile_au.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JpmobileTest</title>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <h1>au</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/application_mobile_docomo.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JpmobileTest</title>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <h1>docomo</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/application_mobile_iphone.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JpmobileTest</title>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <h1>iPhone</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/application_mobile_smart_phone.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JpmobileTest</title>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <h1>SmartPhone</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/application_mobile_softbank.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JpmobileTest</title>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <h1>softbank</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/application_smart_phone.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JpmobileTest</title>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <h1>SmartPhone</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/application_smart_phone_iphone.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name = "viewport" content = "width = device-width, initial-scale = 1, user-scalable = no">
    <title>JpmobileTest</title>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <h1>iPhone</h1>
    <%= yield %>
  </body>
</html>